sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
  - "$HOME/.npm"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
  - codecov
after_success:
  - npm run docs
